### ISSUE TITLE
Passing migrations as strings into careen

### ISSUE THREAD

**Issue by jamesplease** [programble/careen#5]
Hi @programble . I know it's been awhile since you've worked on this, but I'm wondering how much work you think it'd be to build an API like the following...

```js
careen.migrate('some string migration');
```

or with a new flag:

```
careen -A -m "my-migration"
```

I'm doing an ambitious project that involves programmatically building the migrations, and they're never written to the disk (they're stored in *another* database). Do you think this would be easy to update? If so, do you have any guidance on where I could look within careen to make the necessary changes?

Thanks!

**Comment by causal-agent** [comment]
What would be the point? Careen's purpose is to track the migration files which have been applied, and to be able to roll back operations by loading the corresponding files. If passed a string, what could it do that wouldn't be accomplished by running `sqlite3` or `psql`?

**Comment by jamesplease** [comment]
@programble , sorry, my intention isn't to change that behavior. I still want to use that functionality of careen's. Just, instead of the unique identifier being used as a file name that exists somewhere, it would instead be stored in a DB somewhere. I don't need to write to the disk ever (although it would need to be output from careen at some point).

Effectively, I want a lower-level version of careen that the existing public API, which uses the file system, could be built from. Does that make sense?

An updated API might look something like:

```js
// user is able to define how to fetch the migration (reading from file system,
// or DB, or wherever)
careen.migrate(uniqueId);
```

**Comment by causal-agent** [comment]
From what I remember of this code (this turned out to be a project I wrote but never used), it treats a migration and a file or pair of files as synonymous. So it seems like [files.ts](https://github.com/programble/careen/blob/master/lib/files.ts) would need to be reworked as a `Migration` interface instead, with `File` implementing that.

**Comment by jamesplease** [comment]
Alright, cool. I'll take a look there. Thanks @programble !
